version: "3.9"

services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: .
    container_name: fastapi_app
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://fastapi_user:123456@db:5432/fastapi_db
    depends_on:
      - db

volumes:
  postgres_data:
